version: '3.8'
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ../prod_mongoDB:/data/db
    networks:
      - app-network

  app:
    depends_on:
      - mongodb
    image: bearts/express-app:latest
    ports:
      - 6530:6530
    env_file: ./.env
    deploy:
      replicas: 13
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    environment:
      - NODE_ENV=production
      - PORT=6530
      - MONGO_URL=mongodb://root:root@mongodb:27017/
    networks:
      - app-network

  nginx:
    depends_on:
      - app
    image: bearts/express-nginx-prod:latest
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
    attachable: true
