version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data/db:/data/db
    networks:
      - default
  
  app:
    depends_on:
      - mongodb
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: ./app/.env
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=6530
      - MONGO_URL=mongodb://root:root@mongodb:27017/
    stdin_open: true
    tty: true
    networks:
      - default

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - default    

networks:
  default:
    name: express-app
    external: true